auctopusTech/urls.py
from django.contrib import admin
from django.urls import include, path

from core.views import index, contact
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    # path('', index, name='index'),
    path('', include('core.urls')),

    # path('contact/', contact, name='contact'),
    path('books/', include('books.urls')),

    path('dashboard/', include('dashboard.urls')),

]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path

from books import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('items/', views.items, name='items'),

]

core/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_user, name='logout'),
    
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

books/models.py
from django.db import models


from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    

class Book(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    image = models.ImageField(upload_to='items_images', blank=True, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

core/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

books/forms.py
from django import forms

from .models import Book


INPUT_CLASSES = 'w-ful px-10 rounded-xl border'

class NewBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['category', 'name', 'description', 'price', 'image']

        widgets = {
            'category': forms.Select(attrs={'class': INPUT_CLASSES}),
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'description': forms.Textarea(attrs={'class': INPUT_CLASSES}),
            'price': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'image': forms.FileInput(attrs={'class': INPUT_CLASSES}),
        }


class EditBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'description', 'price', 'image']

        widgets = {
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'description': forms.Textarea(attrs={'class': INPUT_CLASSES}),
            'price': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'image': forms.FileInput(attrs={'class': INPUT_CLASSES}),
        }

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Your Username', 'class': 'w-full py-4 px-6 rounded-xl'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Your Password', 'class': 'w-full py-4 px-6 rounded-xl'}))
    


class SignupForm(UserCreationForm):
    

    class Meta:
        model = User
        fields = ['name', 'phone', 'address', 'college', 'username', 'email', 'password1', 'password2']

    
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'w-full py-4 px-6 rounded-xl'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Phone', 'class': 'w-full py-4 px-6 rounded-xl'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Address', 'class': 'w-full py-4 px-6 rounded-xl'}))
    college = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'College', 'class': 'w-full py-4 px-6 rounded-xl'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Your Username', 'class': 'w-full py-4 px-6 rounded-xl'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'Your Email Address', 'class': 'w-full py-4 px-6 rounded-xl'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Your Password', 'class': 'w-full py-4 px-6 rounded-xl'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Repeat Password', 'class': 'w-full py-4 px-6 rounded-xl'}))

books/views.py
from django.shortcuts import get_object_or_404, redirect, render

from django.contrib.auth.decorators import login_required

from books.models import Book, Category
from .forms import EditBookForm, NewBookForm

from django.db.models import Q

# Create your views here.
@login_required
def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Book.objects.all()
    
    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query)|Q(description__icontains=query))

    return render(request, 'books/items.html', {'items': items, 'query':query, 'categories': categories, 'category_id': int(category_id)})

@login_required
def detail(request, pk):
    item = get_object_or_404(Book, pk=pk)
    related_items = Book.objects.filter(category=item.category).exclude(pk=pk)[:3]


    return render(request, 'books/detail.html', {'item': item, 'related_items': related_items})
    

@login_required
def new(request):
    if request.method == 'POST':
        form = NewBookForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('books:detail', pk=item.id)
    else:
        form = NewBookForm()

    return render(request, 'books/form.html', {'form': form, 'title': 'New Item'})



@login_required
def edit(request, pk):
    item = get_object_or_404(Book, pk=pk, created_by=request.user)


    if request.method == 'POST':
        form = EditBookForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('books:edit', pk=item.id)
    else:
        form = EditBookForm(instance=item)

    return render(request, 'books/edit.html', {'form': form, 'title': 'Edit Item'})



@login_required
def delete(request, pk):
    item = get_object_or_404(Book, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

core/views.py
from django.shortcuts import redirect, render


from books.models import Category, Book

from .forms import SignupForm

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request):
    items = Book.objects.all()[:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {'categories': categories, 'items': items,})


def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('/login/')

dashboard/views.py
from django.shortcuts import render, get_object_or_404


from django.contrib.auth.decorators import login_required

from books.models import Book

# Create your views here.

@login_required
def index(request):
    items = Book.objects.all()

    return render(request, 'dashboard/index.html', {'items': items})

books/templates/books/detail.html
{% extends 'core/base.html' %}

{% block title %} {{item.name}} {% endblock %}


{% block content %}

    <div class="grid grid-cols-4 gap-2">
        <div class='col-span-2'>
            {% comment %} <img src="{{item.image.url}}" class="rounded-xl" style="max-height: 700px; object-fit: contain; align-items: center; width: 600px;"> {% endcomment %}
        </div>
        <div class="col-span-2 p-5 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl"> {{item.name}} </h1>
            <p class="text-gray-500"><strong> Price :</strong> {{item.price}}</p>
            <p class="text-gray-500"><strong> Seller :</strong> 
                {{item.created_by.username}}
            </p>
        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500"> Description :</strong> <br>
                {{item.description}}
            </p>
        {% endif %}

        {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p> This is your item!</p>

                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl"> Edit </a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl"> Delete </a>
            </div>
        {% endif %}
        </div>
    </div>
    <div class="mt-6 px-6 py-6 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related Items</h2>
    
        <div class="grid grid-cols-3 gap-2">
            {% for item in related_items %}
            <div class="card px-4" style="max-width: 500px; height: 700px;">
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        {% comment %} <img class="card-img-top rounded-t-xl bg-white"
                            style="height: 350px; object-fit: contain; align-items: center; width: 100%;"
                            src="{{item.image.url}}" alt="Card image cap"> {% endcomment %}
                    </div>
                    <div class="p-6 bg-white rounded-b-xl" style="height: 250px; line-height: 50px;">
                        <h2 class="card-title text-2xl" style="font-size: medium; line-height: 20px;"><b>{{item.name}}</b>
                        </h2>
                        <p class="card-text text-gray-500">Price : {{item.price}}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    
{% endblock content %}
    

books/templates/books/form.html
{% extends 'core/base.html' %}

{% block title %}{{title}}{% endblock %}


{% block content %}
    <h1 class="mb-6 text-3xl">{{title}}</h1>
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-10 space-x-10">
            {{form.as_p}}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{field.errors}}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white"> Submit </button>
    </form>
{% endblock %}

books/templates/books/items.html
{% extends 'core/base.html' %}


{% block title %} Books {% endblock %}


{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4">
        <div class="col-span-1 p-6 bg-gray-100 rounded-xl">
            <form method="get" action="{% url 'item:items' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{query}}" placeholder="Find a bike, a chair or car...">
                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl"> Search </button>
            </form>

            <hr class="my-6">
            <p class="font-semibold"> Categories </p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200 {% endif %}">
                        <a href="{% url 'item:items' %}?query={{query}}&category={{category.id}}">{{category.name}}</a>
                    </li>
                {% endfor %}
            </ul>

            
            <hr class="my-6">
            <p class="font-semibold"> Clear filters </p>
            <ul>
                <li><a href="{% url 'item:items' %}" class="mt-2 py-2 px-4 inline-block bg-yellow-500 text-lg rounded-xl text-white"> Clear </a></li>
            </ul>

        </div>

        
        <div class="col-span-3 bg-gray-100 p-5 rounded-xl">
            <div class="grid grid-cols-3 gap-2">
                {% for item in items %}
                <div class="card px-4" style="max-width: 500px; height: 650px;">
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            {% comment %} <img class="card-img-top rounded-t-xl bg-white" style="height: 350px; object-fit: contain; align-items: center; width: 100%;" src="{{item.image.url}}" alt="Card image cap"> {% endcomment %}
                        </div>
                        <hr>
                        <div class="p-6 rounded-b-xl bg-white" style="height: 250px; line-height: 50px;">
                            <h2 class="card-title text-2xl" style="font-size: medium; line-height: 20px;"><b>{{item.name}}</b></h2>
                            <p class="card-text text-gray-500">Price : {{item.price}}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock title %} | AuctopusTech </title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold"> AuctopusTech </a>

            <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500"> New Boook </a>
                <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500"> Browse </a>
            {% if request.user.is_authenticated %}
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700"> Dashboard </a>
                <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-gray-700"> Log Out </a>
            {% else %}
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700"> Log In </a>
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"> Sign Up </a>
            {% endif %}
            </div>
        </nav>
        <div class="px-6 py-6">
            {% block content %}
            
            {% endblock content %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400"> About </h3>
                
                <p class="text-lg text-gray-500" style="font-size:14px"> lorem impsum lorem impsum lorem impsum lorem impsum lorem impsum lorem impsum </p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400"> Menu </h3>
                
                <ul class="space-y-.5">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700" style="font-size:12px"> About </a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700" style="font-size:12px"> Privacy Policy </a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700" style="font-size:12px"> Contact </a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700" style="font-size:12px"> Terms of Uses </a></li>
                </ul>
            
            </div>
        </footer>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}


{% block title %} Welcome {% endblock title %}

{% block content %}
    <div class ="mt-6 px-6 py-6 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Books</h2>
    
        <div class="grid grid-cols-3 gap-2">
             {% for item in items %}
                <div class="card px-4" style="max-width: 500px; height: 700px;">
                    <a href="{% url 'item:detail' item.id %}">
                        <div >
                            {% comment %} <img class="card-img-top rounded-t-xl bg-white" style="height: 350px; object-fit: contain; align-items: center; width: 100%;" src="{{item.image.url}}" alt="Card image cap"> {% endcomment %}
                        </div>
                        <div class="p-6 bg-white rounded-b-xl" style="height: 250px; line-height: 50px;">
                            <h2 class="card-title text-2xl" style="font-size: medium; line-height: 20px;"><b>{{item.name}}</b></h2>
                            <p class="card-text text-gray-500">Price : {{item.price}}</p>    
                        </div>
                    </a>
                </div>
             {% endfor %}
        </div>
    </div>
    <div class="mt-6 px-6 py-6 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Books</h2>
    
        <div class="grid grid-cols-5 gap-2 margin-left-auto">
            {% for category in categories %}
                <div class="card px-4" style="max-width: 500px; height: 700px;">
                    <a href="#">
                        <div class="card-body p-6 bg-white rounded-b-xl" style="height: 100px; line-height: 50px;">
                            <h2 class="card-title text-2xl" style="font-size: medium; line-height: 20px;"><b>{{category.name}}</b></h2>
                            <p class="card-text text-gray-500">{{category.items.count}} Books</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %} Log In {% endblock %}

{% block content %}

    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl"> Log In</h1>

        <form method="post" action=".">
            {% csrf_token %}
            
            
            <div class="mb-3">
                <label class="inline-block mb-2"> Username </label> <br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2"> Password </label> <br>
                {{ form.password }}
            </div>
            

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{field.errors}}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white"> Submit </button>
        </form>
    </div>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %} Sign Up {% endblock %}

{% block content %}

    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl"> Sign Up</h1>

        <form method="post" action=".">
            {% csrf_token %}
            
            <div class="mb-3">
                <label class="inline-block mb-2"> Name </label> <br>
                {{ form.name }}
            </div>  
            <div class="mb-3">
                <label class="inline-block mb-2"> Phone </label> <br>
                {{ form.phone }}
            </div>  
            <div class="mb-3">
                <label class="inline-block mb-2"> Address </label> <br>
                {{ form.address }}
            </div>  
            <div class="mb-3">
                <label class="inline-block mb-2"> College </label> <br>
                {{ form.college }}
            </div>  
            <div class="mb-3">
                <label class="inline-block mb-2"> Email </label> <br>
                {{ form.email }}
            </div>  
            <div class="mb-3">
                <label class="inline-block mb-2"> Username </label> <br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2"> Password </label> <br>
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2"> Confirm Password </label> <br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{field.errors}}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white"> Submit </button>
        </form>
    </div>

{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'core/base.html' %}


{% block title %} Dashboard {% endblock title %}

{% block content %}
<div class="mt-6 px-6 py-6 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">My Books</h2>

    <div class="grid grid-cols-3 gap-2">
        {% for item in items %}
        <div class="card px-4" style="max-width: 500px; height: 700px;">
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    {% comment %} <img class="card-img-top rounded-t-xl bg-white"
                        style="height: 350px; object-fit: contain; align-items: center; width: 100%;"
                        src="{{item.image.url}}" alt="Card image cap"> {% endcomment %}
                </div>
                <div class="p-6 bg-white rounded-b-xl" style="height: 250px; line-height: 50px;">
                    <h2 class="card-title text-2xl" style="font-size: medium; line-height: 20px;"><b>{{item.name}}</b>
                    </h2>
                    <p class="card-text text-gray-500">Price : {{item.price}}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}